### ISSUE TITLE
Units - Symbols are missing or wrong displayed on the map

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#170] opened 2020-02-25 08:11 UTC
The following symbols for units are missing or wrong displayed on the map:

SIDC  2525c (following example all with the Modifier (F) for friend on the Postion 2) /  Hierachy Code:

SFGPUCAAS***** / WAR.GRDTRK.UNT.CBT.AARM.ARMD.AAST
SFGPUCAAOS***** / WAR.GRDTRK.UNT.CBT.AARM.MOT.AAST
**"V" (for air assault) in the symbol isn't on the right position**

SFGPUCFTS-***** / WAR.GRDTRK.UNT.CBT.FLDART.TGTAQ.SND
**symbol is not a unit - only a line is creatable**

SFGPUUABR-***** / WAR.GRDTRK.UNT.CS.CBRN.BIO.RECEQP
**"B" should be more on the left side (not in the middle)**

SFGPUUMS--***** / WAR.GRDTRK.UNT.CS.MILINT.SIGINT
**"MI" is in the wrong place, the icon in the middle of the unit is displayed without a circle**

SFGPUUMSEA***** | WAR.GRDTRK.UNT.CS.MILINT.SIGINT.ECW.ARMWVH
**"EW" is in the wrong place, more left/up in vehicle symbol**

SFGPUSXR--***** | WAR.GRDTRK.UNT.CSS.MAINT.RCY
SFGPUSXRT-***** | WAR.GRDTRK.UNT.CSS.MAINT.RCY.THT
SFGPUSXRC-***** | WAR.GRDTRK.UNT.CSS.MAINT.RCY.CRP
**only 2 wheels are in the symbol, not 4 wheels**

**Comment by harrywipperfuerth** [comment] 2020-06-24 07:21
### **_Update 23jun20_**
(the entry of 25feb20 must therefore be regarded as oboslet):

Due to the change from version 0.5.4 to version 0.6.0/OL and the resulting reimplementation of the symbols 2525C, the following incorrect representations in the unit range were found during the check:

The following symbols for units are **_wrong displayed_** on the map:

SIDC 2525c (following example all with the Modifier (F) for friend on the Postion 2) / Hierachy Code:

SFGPUCAAS***** / WAR.GRDTRK.UNT.CBT.AARM.ARMD.AAST
SFGPUCAWS-***** / WAR.GRDTRK.UNT.CBT.ARM.WHD.AAST
**"V" (for air assault) in the symbol isn't on the right position**

SFGPUUABR-***** / WAR.GRDTRK.UNT.CS.CBRN.BIO.RECEQP
**"B" should be more on the left side (not in the middle)**

SFGPUUMS--***** / WAR.GRDTRK.UNT.CS.MILINT.SIGINT
**"MI" is in the wrong place, the icon in the middle of the unit is displayed without a circle**

SFGPUUMSEA***** / WAR.GRDTRK.UNT.CS.MILINT.SIGINT.ECW.ARMWVH
**"EW" is in the wrong place, more left/up in vehicle symbol**

SFGPUSXR--***** / WAR.GRDTRK.UNT.CSS.MAINT.RCY
SFGPUSXRT-***** / WAR.GRDTRK.UNT.CSS.MAINT.RCY.THT
SFGPUSXRC-***** / WAR.GRDTRK.UNT.CSS.MAINT.RCY.CRP
**only 2 wheels are in the symbol, not 4 wheels**

SFGPUCDMLA***** / WAR.GRDTRK.UNT.CBT.ADF.MSL.LIT.MOT
**horizontal line in missile symbol is missing**

SFGPUUACRS***** | WAR.GRDTRK.UNT.CS.CBRN.CML.RECON.WAVS
**"RS" should be inside of the armour chain symbol**

**Comment by dehmer** [comment] 2020-11-15 18:03
Yes, most icons here slightly off. This is an upstream dependency to Beckman.
I'm not sure how to deal with this.

Two questions:
* Is it possible that 2525D has slightly different icons than C?
* How "bad" are the differences for a user? Are some/all icons unrecognizable?

<img width="319" alt="Screenshot 2020-11-15 at 18 57 27" src="https://user-images.githubusercontent.com/322462/99192787-1dd3aa80-2775-11eb-8f7e-b55ea4437c99.png">


 1. SFGPUCAAS-*****: slightly wrong icon (upstream, Måns Beckman)
 2. SFGPUCAAOS*****: slightly wrong icon (upstream, Måns Beckman)
 3. SFGPUCFTS-*****: cannot reproduce; top hit in palette "target acquisition sound"
 4. SFGPUUABR-*****: slightly wrong icon (upstream, Måns Beckman)
 5. SFGPUUMS--*****: slightly wrong icon (upstream, Måns Beckman)
 6. SFGPUUMSEA*****: slightly wrong icon (upstream, Måns Beckman)
 7. SFGPUSXR--*****: slightly wrong icon (upstream, Måns Beckman)
 8. SFGPUSXRT-*****: slightly wrong icon (upstream, Måns Beckman)
 9. SFGPUSXRC-*****: slightly wrong icon (upstream, Måns Beckman)
10. SFGPUCAWS-*****: slightly wrong icon (upstream, Måns Beckman)
11. SFGPUCDMLA*****: cannot reproduce; looks good to me
12. SFGPUUACRS*****: slightly wrong icon (upstream, Måns Beckman)

**Comment by harrywipperfuerth** [comment] 2020-11-16 08:26
The symbols below represent the MIL-STD 2525D rather than the MIL-STD 2525C:

**No. 1. SFGPUCAAS-*****
**No. 2. SFGPUCAAOS*******
**No. 4. SFGPUUABR-*******
**No. 10. SFGPUCAWS-*********

The reason is that in MIL-STD 2525D "Air assault", "Biological" are no longer displayed as a separate species symbol, but is now placed as Modifier 1 in the upper part of the symbol.


**No. 3. SFGPUCFTS-*******
**No. 12. SFGPUUACRS*******

The symbols are now displayed correctly on the map.


**No. 5. SFGPUUMS--*******

The symbol in ODIN does not exactly match the representation in MIL-STD 2525C, but is readable for the user.

The representation in MIL-STD 2525D is different, because "Signal Intelligence" is placed as Modifier 1 in the upper part of the symbol.

![grafik](https://user-images.githubusercontent.com/49548300/99226914-d6880100-27ea-11eb-8355-7dbcd9e2564c.png)


**No. 6. SFGPUUMSEA*********
**No. 7. SFGPUSXR--*********
**No. 8. SFGPUSXRT-*******
**No. 9. SFGPUSXRC-*******

The symbol in ODIN does not exactly match the representation in MIL-STD 2525C, but is readable for the user.

In MIL-STD 2525D there is no longer an example of a representation for this symbol.


**No. 11. SFGPUCDMLA*******

The symbol in ODIN is not quite exatly the same as in MIL-STD 2525C (the dash in the ammunition mark is missing), but is considered legible to the user.

In MIL-STD 2525D there is no longer an example of a representation for this symbol.

**Comment by dehmer** [comment] 2020-11-16 08:39
So, we're good for now?
Can we close this issue?

**Comment by dehmer** [comment] 2020-11-16 08:40
I will create a new issue containing all symbols, which should be corrected.

**Comment by dehmer** [comment] 2020-11-16 10:12
No further actions required.
Closing.

**Closed by dehmer** 2020-11-16 10:12 UTC
Labels: accepted, issue, upstream
